cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
cobc -x -free *.cobc -o main
